########################################
# Override the default preheats
########################################

[preheat PLA]
extruder: 150
heater_bed: 60
chamber_fan: 35
gcode: SET_PIN PIN=nevermore VALUE=0

[preheat ABS]
extruder: 150
heater_bed: 105
chamber_fan: 60
gcode: SET_PIN PIN=nevermore VALUE=1

[preheat PA]
extruder: 150
heater_bed: 100
chamber_fan: 60
gcode: SET_PIN PIN=nevermore VALUE=1
